services:
  odesskij_app.faker_factory:
    class: Odesskij\Bundle\AppBundle\Service\FakerFactory

  odesskij_app.faker:
    class:   Faker\Generator
    factory: ["@odesskij_app.faker_factory", create]